import 'package:flutter/material.dart';
import 'app_scope.dart';

class AppLanguage {
  const AppLanguage({
    required this.code,
    required this.title,
    required this.subtitle,
  });

  final String code;
  final String title;
  final String subtitle;
}

class AppLanguages {
  static const AppLanguage russian = AppLanguage(
    code: 'ru',
    title: 'Русский',
    subtitle: 'Russian',
  );

  static const AppLanguage english = AppLanguage(
    code: 'en',
    title: 'English',
    subtitle: 'English',
  );

  static const AppLanguage belarusian = AppLanguage(
    code: 'be',
    title: 'Беларуская',
    subtitle: 'Беларуская',
  );

  static const List<AppLanguage> all = <AppLanguage>[
    russian,
    english,
    belarusian,
  ];
}

class AppLocalizations {
  AppLocalizations(this.locale);

  final String locale;

  static AppLocalizations of(BuildContext context) {
    final controller = AppScope.of(context);
    return AppLocalizations(controller.appLanguage);
  }

  static final Map<String, Map<String, String>> _translations = {
    'ru': {
      'language': 'Язык',
      'language_interface': 'ЯЗЫК ИНТЕРФЕЙСА',
      'privacy': 'Конфиденциальность',
      'passcode': 'Код-пароль',
      'auto_cleanup': 'Автоочищение памяти',
      'auto_cleanup_title': 'Автоочистка памяти',
      'what_to_delete': 'Что удалять автоматически',
      'nothing_selected': 'Ничего не выбрано',
      'type': 'тип',
      'types': 'типа',
      'type_many': 'типов',
      'video': 'Видео',
      'photo': 'Фото',
      'files': 'Файлы',
      'stickers': 'Стикеры',
      'other_cleanup': 'Прочее',
      'cleanup_warning':
          'Важно: удаляется только то, что Вы выбрали и в то время, какое Вы поставили. Вы сможете заново скачать из чатов то, что удалено.',
      'cleanup_time': 'Время автоудаления',
      'off': 'Выключено',
      'after_1_day': 'Через 1 день',
      'after_5_days': 'Через 5 дней',
      'after_10_days': 'Через 10 дней',
      'after_20_days': 'Через 20 дней',
      'done': 'Готово',
      'cancel': 'Отмена',
      'back': 'Назад',
      'settings': 'Настройки',
      'profile': 'Профиль',
      'help': 'Помощь',
      'about': 'О приложении',
      'memory_usage': 'Использование памяти',
      'clear_cache': 'Очистить кэш',
      'clear_cache_confirm':
          'Все медиа останутся в облаке MyCircle, при необходимости Вы сможете загрузить их снова из чатов',
      'cancel_btn': 'Отмена',
      'clear_btn': 'Очистить',
      'no_downloaded_media': 'Нет скачанного медиа',
      'download': 'Скачать',
      'downloaded_to_mycircle': 'Скачано в MyCircle',
      'download_failed': 'Не удалось скачать',
      'download_error': 'Ошибка скачивания',
      'max_cache_size': 'Максимальный размер кэша',
      'max_cache_desc':
          'Если размер кэша превысит этот лимит, то самые старые из неиспользуемых медиа будут удалены из памяти устройства',
      'media': 'Медиа',
      'files_tab': 'Файлы',
      'music': 'Музыка',
      'occupied': 'Занято',
      'files_soon': 'Файлы: скоро',
      'music_soon': 'Музыка: скоро',
      'disable_passcode': 'Отключить код-пароль',
      'change_passcode': 'Изменить код-пароль',
      'passcode_settings': 'Настройки код-пароля',
      'auto_lock': 'Автоблокировка',
      'auto_lock_immediately': 'Сразу',
      'auto_lock_after_1_min': 'Через 1 минуту',
      'auto_lock_after_5_min': 'Через 5 минут',
      'auto_lock_after_15_min': 'Через 15 минут',
      'auto_lock_after_1_hour': 'Через 1 час',
      'auto_lock_after_5_hours': 'Через 5 часов',
      'enter_passcode': 'Введите код-пароль',
      'set_passcode': 'Установите код-пароль',
      'confirm_passcode': 'Подтвердите код-пароль',
      'passcodes_dont_match': 'Коды не совпадают',
      'passcode_changed': 'Код-пароль изменён',
      'passcode_disabled': 'Код-пароль отключён',
      'passcode_warning':
          'Важно: если Вы забудете код доступа, Вам придётся переустановить приложение, и просить ключи сервера занова.',
      'enter_new_passcode': 'Введите новый код-пароль',
      'navigation_panel': 'Панель навигации',
      'change_navigation_panel': 'Изменить панель навигации',
      'chat_settings': 'Настройка чатов:',
      'change_wallpaper': 'Изменить обои',
      'memory_and_security': 'Память и безопасность',
      'ios_navigation_panel': 'Панель навигации IOS',
      'ios_navigation_panel_desc':
          'Частичная копия панели навигации iOS 26 с технологией Liquid Glass ("Жидкое стекло"). Использование на устройствах с невысокой производительностью не рекомендуется: это может вызвать рост нагрузки на систему.',
      'invert_lens': 'Инвертировать линзу по вертикали',
      'invert_lens_desc':
          'Если при удержании и перемещении выделения иконка/текст отображаются вверх ногами — переключи этот параметр.',
      'save': 'Сохранить',
      'settings_page': 'Настройки',
      'your_name': 'Ваше имя',
      'birthday': 'День рождения',
      'your_birth_date': 'Дата Вашего рождения',
      'specify': 'Указать',
      'appearance': 'Оформление',
      'notifications': 'Уведомления',
      'allow_notifications': 'Разрешить уведомления в настройках ОС',
      'start_chat': 'Начать общение',
      'nothing_found': 'Ничего не найдено',
      'chat_data_copied': 'Данные чата скопированы',
      'share': 'Поделиться',
      'shop': 'Магазин',
      'no_sticker_packs': 'Пока нет наборов стикеров',
      'added': 'Добавлено',
      'add': 'Добавить',
      'get': 'Получить',
      'cache_error': 'Кэш: ',
      'edit': 'Изм.',
      'notification_permission': 'Разрешите уведомления в настройках ОС',
      'shop_load_error': 'Ошибка загрузки магазина: ',
      'no_data': 'Нет данных',
      'other_settings': 'Остальное',
      'questions_about_mycircle': 'Вопросы о MyCircle',
      'close_search': 'Закрыть поиск',
      'search': 'Поиск',
      'energy_saving': 'Энергосбережение',
      'energy_saving_settings_later':
          'Настройки энергосбережения будут добавлены позже.',
      'warning': 'Предупреждение',
      'delete_data_warning':
          'Ваши данные: имя, дата рождения, данные из чатов, Sup. API и Sup. pub_key будут удалены. Вам придётся заново входить в сервер какого-нибудь пользователя и проходить регистрацию.',
      'name': 'Имя',
      'accessibility': 'Специальные возможности',
      'enable_notifications': 'Включить уведомления',
      'disable_notifications': 'Выключить уведомления',
      'data_and_memory': 'Данные и память',
      'language_short': 'Язык',
      'mycircle_channel': 'Канал MyCircle',
      'sticker_load_error': 'Ошибка загрузки стикеров:',
      'add_sticker_packs_hint':
          'Добавь наборы стикеров в «Магазине», чтобы они появились здесь',
      'clear_cache_with_size': 'Очистить кэш',
      'cache_prefix': 'Кэш: ',
      'byte_unit_b': 'Б',
      'byte_unit_kb': 'КБ',
      'byte_unit_mb': 'МБ',
      'byte_unit_gb': 'ГБ',
      'byte_unit_tb': 'ТБ',
      'gb_unit': 'ГБ',
      'tapflow': 'TapFlow',
      'file_saved': 'Файл сохранён.',
      'error': 'Ошибка',
      'transfer_failed': 'Не удалось выполнить передачу.',
      'hint': 'Подсказка',
      'tapflow_share_hint':
          'Для отправки используйте системную «Поделиться» и выберите TapFlow.',
      'progress': 'Прогресс',
      'ready_to_receive': 'Готов к приёму',
      'tap_detected': 'Касание обнаружено',
      'transfer_request': 'Запрос на передачу',
      'connecting': 'Подключение',
      'transferring': 'Передача',
      'tapflow_standby': 'Откройте TapFlow, чтобы быть готовым к приёму.',
      'tapflow_waiting':
          'Поднесите телефон к устройству отправителя.\nTapFlow автоматически поймёт контекст.',
      'establishing_connection': 'Устанавливаю соединение…',
      'wants_to_transfer': 'хочет передать',
      'connecting_to_sender': 'Подключаюсь к отправителю…',
      'receiving_file': 'Получаю файл…',
      'file_received': 'Файл получен и сохранён.',
      'device': 'Устройство',
      'supabase_data': 'Данные Supabase',
      'decline': 'Отклонить',
      'accept': 'Принять',
      'my_profile': 'Мой профиль',
      'switch_to_light_theme': 'Переключить на дневную тему',
      'switch_to_dark_theme': 'Переключить на ночную тему',
      'reset': 'Сбросить',
      'failed_to_apply_drawing': 'Не удалось применить рисунок',
      'clear_all': 'Очистить всё',
      'no_media': 'Нет медиа',
      'sticker_label': 'Стикер',
      'media_label': 'Медиа',
      'load_btn': 'Загрузить',
      'chat_fallback': 'Чат',
      'search_chats_hint': 'Поиск чатов',
      'chats': 'Чаты',
      'delete_chat_title_single': 'Удалить чат',
      'delete_chat_title_plural': 'Удалить чаты',
      'remove_chat_confirm_single': 'Убрать чат из списка на устройстве?',
      'remove_chat_confirm_plural': 'Убрать \$count чатов из списка на устройстве?',
      'delete_btn': 'Удалить',
      'all_filter': 'Все',
      'channels': 'Каналы',
      'notes': 'Заметки',
      'you': 'Вы',
      'interlocutor': 'Собеседник',
      'photo_reply': 'Фото',
      'message_reply': 'Сообщение',
      'add_chat_first_hint': 'Сначала добавьте чат через «Добавить чат»',
      'editing': 'Редактирование',
      'no_messages_yet': 'Пока нет сообщений',
      'failed_to_decrypt': 'Не удалось расшифровать сообщение',
      'members_count': '\$count участников',
      'chat_token_label': 'Токен чата',
      'chat_id_label': 'ID чата',
      'members_section': 'Участники',
      'files_section': 'Файлы',
      'not_working_yet': 'Пока не работает',
      'members_not_available': 'Участники недоступны (в Supabase нет колонки member_tokens в таблице chats)',
      'no_one_here_yet': 'Пока никого нет',
      'hd_photo_info': 'Фотография будет в высоком разрешении.',
      'sd_photo_info': 'Фотография будет в обычном разрешении.',
      'add_caption_hint': 'Добавить подпись…',
      'downloaded_mycircle': 'Скачано в MyCircle',
      'download_failed_label': 'Не удалось скачать',
      'download_error_label': 'Ошибка скачивания: \$e',
      'download_title': 'Скачать',
      'sticker_reply': 'Стикер',
      'notes_empty': 'Вы ещё ничего не добавили в заметки',
      'edit_message_label': 'Изменить сообщение',
      'bold': 'Жирный',
      'strikethrough': 'Зачеркнутый',
      'hidden_spoiler': 'Скрытый (спойлер)',
      'reply_to_prefix': 'В ответ',
      'message_hint': 'Сообщение',
      'no_connection_error': 'Подключение к сети отсутствует или плохая связь. Проверьте свою сеть',
      'error_loading_messages': 'Ошибка загрузки сообщений',
      'copied': 'Скопировано',
      'delete_message_title': 'Удалить сообщение',
      'delete_message_confirm': 'Вы точно хотите удалить это сообщение?',
      'failed_to_delete': 'Не удалось удалить: \$e',
      'failed_to_send_message': 'Не удалось отправить сообщение: \$e',
      'edge_function_no_url': 'Edge Function не вернула raw_url',
      'failed_to_send_file': 'Не удалось отправить файл',
      'failed_to_open_gallery_file': 'Не удалось открыть файл из галереи',
      'no_gallery_access': 'Нет доступа к галерее',
      'failed_to_send_sticker': 'Не удалось отправить стикер',
      'refresh': 'Обновить',
      'invalid_link': 'Некорректная ссылка',
      'failed_to_open_link': 'Не удалось открыть ссылку',
      'dark_mode': 'Тёмный режим',
      'me': 'Я',
      'quick_access': 'Быстрый доступ',
      'close_tooltip': 'Закрыть',
      'in_development': 'В разработке',
      'bottom_menu': 'Нижнее меню',
      'day_picker': 'День',
      'month_picker': 'Месяц',
      'year_picker': 'Год',
      'confirm_btn': 'Подтвердить',
      'create_chat': 'Создать чат',
      'join_chat': 'Присоединиться к чату',
      'search_label': 'Поиск',
      'title_label': 'Название',
      'name_prefix': 'Название: \$title',
      'server': 'Сервер',
      'server_setup_desc': 'Войдите в сервер или создайте его, чтобы начать общение с близкими людьми',
      'create_server': 'Создать сервер',
      'login_to_server': 'Войти в сервер',
      'docs': 'Документация',
      'server_docs_desc': 'Прочитайте документацию по созданию сервера, чтобы всё работало',
      'supabase_url_hint': 'вставляйте ссылку без "/rest/v1/"',
      'continue_btn': 'Продолжить',
      'save_error': 'Ошибка сохранения: \$e',
      'server_error': 'Ошибка сервера: \$e',
      'enter_via_tapflow': 'Ввести через TapFlow',
      'firebase_note': 'Firebase уже используется в приложении (push-уведомления), но эти данные настраиваются в проекте и сюда вводить не нужно.',
      'what_to_call_you': 'Как вас называть?',
      'name_hint': 'Имя',
      'theme_and_color_prompt': 'Какая вас устраивает тема и цвет кнопок?',
      'light': 'Белая',
      'dark': 'Тёмная',
      'button_colors': 'Цвет кнопок',
      'choose_input_field': 'Выберите поле ввода',
      'normal': 'Обычное',
      'advanced': 'Расширенное',
      'ios_panel': 'IOS панель',
      'choose_navigation': 'Выберите панель навигации',
      'sliding': 'Выдвигающиеся',
      'thanks_for_your_time': 'Спасибо за уделённое время',
      'copy_btn': 'Копировать',
      'loading': 'Загрузка...',
      'registration': 'Регистрация',
      'file_fallback': 'файл',
      'token_label': 'Токен',
      'remove_tooltip': 'Удалить',
      'token_n_label': 'Токен \$n',
      'add_token_tooltip': 'Добавить токен',
      'prompt_label': 'Промт',
      'nameless': 'Без имени',
      'info_section': 'Информация',
      'not_specified': 'Не указано',
      'birth_date_label': 'Дата рождения',
      'send_via_tapflow': 'Передать через TapFlow',
      'copy_and_share': 'Скопировать и поделиться',
      'share_btn': 'поделиться',
      'stickers_count': 'Стикеров: \$count',
      'pack_added': 'Набор добавлен',
      'pack_download_failed': 'Не удалось скачать набор',
      'fill_all_fields': 'Заполните все поля',
      'problem_too_long': 'Краткая проблема: максимум 20 символов',
      'invalid_email': 'Введите корректную почту',
      'sent': 'Отправлено',
      'send_error': 'Ошибка отправки. Попробуйте позже.',
      'problem_label': 'Краткая проблема',
      'email_label': 'Почта',
      'problem_hint': 'Подробно опишите проблему',
      'send_btn': 'Отправить',
      'unsubscribe_channel': 'Отписка от канала',
      'unsubscribe_confirm': 'Вы точно хотите покинуть канал MyCircle?',
      'leave_btn': 'Покинуть',
      'search_in_chat_hint': 'Искать в чате',
      'subscribed': 'Подписаны',
      'subscribe': 'Подписаться',
      'description_label': 'описание',
      'channel_description': 'Новости по мессенджеру, изменения и другие обновления',
      'dev_notice_title': 'Оповещение',
      'dev_notice_text': 'Данный мессенджер сделан не до конца и, возможно, выглядит некрасиво, имеются ошибки и многое другое. Поэтому, пожалуйста, сообщайте об этих недочётах и предлагайте свои идеи, чтобы мессенджер было удобным всем и вся.',
      'close_btn': 'Закрыть',
      'version_label': 'Версия \$version',
      'chat_exists_error': 'Чат с таким ID уже существует',
      'create_chat_error': 'Не удалось создать чат',
      'chat_not_found_server': 'Чат с таким ID не найден на сервере',
      'no_chat_uuid': 'Не удалось получить UUID чата',
      'invalid_chat_token': 'Неверный токен чата',
      'error_fallback': 'Ошибка',
      'chat_id_required': 'ID чата обязателен',
      'chat_name_required': 'Название чата обязательно',
      'chat_token_required': 'Токен чата обязателен',
      'sup_api_label': 'Sup. API',
      'sup_pub_key_label': 'Sup. pub_key',
      'channel_left': 'Вы покинули канал',
      'january': 'января',
      'february': 'февраля',
      'march': 'марта',
      'april': 'апреля',
      'may': 'мая',
      'june': 'июня',
      'july': 'июля',
      'august': 'августа',
      'september': 'сентября',
      'october': 'октября',
      'november': 'ноября',
      'december': 'декабря',
      'about_text':
          'MyCircle — это децентрализованная платформа для обмена сообщениями, ориентированная на обеспечение полной приватности и суверенитета пользовательских данных.\n'
          '\n'
          'Ключевые принципы:\n'
          'Собственная инфраструктура: В основе MyCircle лежит концепция персональных серверов. Вы самостоятельно разворачиваете серверную часть, что позволяет вам полностью контролировать среду общения и круг участников.\n'
          'Конфиденциальность: Разработчик приложения не осуществляет сбор, хранение или обработку ваших данных. Вся информация (сообщения, медиафайлы, метаданные) хранится исключительно на сервере, выбранном или созданном пользователем.\n'
          'Безопасность через доверие: Вы сами определяете, кому предоставить доступ к вашему серверу, исключая возможность несанкционированного доступа со стороны третьих лиц или глобальных провайдеров.\n'
          '\n'
          'Технологический стек:\n'
          'Приложение разработано на фреймворке Flutter, что обеспечивает высокую производительность, стабильность работы и отзывчивость интерфейса.',
    },
    'en': {
      'language': 'Language',
      'language_interface': 'INTERFACE LANGUAGE',
      'privacy': 'Privacy',
      'passcode': 'Passcode',
      'auto_cleanup': 'Auto cleanup',
      'auto_cleanup_title': 'Auto cleanup',
      'what_to_delete': 'What to delete automatically',
      'nothing_selected': 'Nothing selected',
      'type': 'type',
      'types': 'types',
      'type_many': 'types',
      'video': 'Video',
      'photo': 'Photo',
      'files': 'Files',
      'stickers': 'Stickers',
      'other_cleanup': 'Other',
      'cleanup_warning':
          'Important: only what you selected and at the time you set will be deleted. You can re-download deleted items from chats.',
      'cleanup_time': 'Auto deletion time',
      'off': 'Off',
      'after_1_day': 'After 1 day',
      'after_5_days': 'After 5 days',
      'after_10_days': 'After 10 days',
      'after_20_days': 'After 20 days',
      'done': 'Done',
      'cancel': 'Cancel',
      'back': 'Back',
      'settings': 'Settings',
      'profile': 'Profile',
      'help': 'Help',
      'about': 'About',
      'memory_usage': 'Memory usage',
      'clear_cache': 'Clear cache',
      'clear_cache_confirm':
          'All media will remain in the MyCircle cloud, you can download them again from chats if needed',
      'cancel_btn': 'Cancel',
      'clear_btn': 'Clear',
      'no_downloaded_media': 'No downloaded media',
      'download': 'Download',
      'downloaded_to_mycircle': 'Downloaded to MyCircle',
      'download_failed': 'Download failed',
      'download_error': 'Download error',
      'max_cache_size': 'Maximum cache size',
      'max_cache_desc':
          'If the cache size exceeds this limit, the oldest unused media will be deleted from device memory',
      'media': 'Media',
      'files_tab': 'Files',
      'music': 'Music',
      'occupied': 'Occupied',
      'files_soon': 'Files: coming soon',
      'music_soon': 'Music: coming soon',
      'disable_passcode': 'Disable passcode',
      'change_passcode': 'Change passcode',
      'passcode_settings': 'Passcode settings',
      'auto_lock': 'Auto-lock',
      'auto_lock_immediately': 'Immediately',
      'auto_lock_after_1_min': 'After 1 minute',
      'auto_lock_after_5_min': 'After 5 minutes',
      'auto_lock_after_15_min': 'After 15 minutes',
      'auto_lock_after_1_hour': 'After 1 hour',
      'auto_lock_after_5_hours': 'After 5 hours',
      'enter_passcode': 'Enter passcode',
      'set_passcode': 'Set passcode',
      'confirm_passcode': 'Confirm passcode',
      'passcodes_dont_match': 'Passcodes do not match',
      'passcode_changed': 'Passcode changed',
      'passcode_disabled': 'Passcode disabled',
      'passcode_warning':
          'Important: if you forget your passcode, you will need to reinstall the app and request server keys again.',
      'enter_new_passcode': 'Enter new passcode',
      'navigation_panel': 'Navigation panel',
      'change_navigation_panel': 'Change navigation panel',
      'chat_settings': 'Chat settings:',
      'change_wallpaper': 'Change wallpaper',
      'memory_and_security': 'Memory and security',
      'ios_navigation_panel': 'IOS navigation panel',
      'ios_navigation_panel_desc':
          'Partial copy of iOS 26 navigation panel with Liquid Glass technology. Not recommended for low-performance devices: this may increase system load.',
      'invert_lens': 'Invert lens vertically',
      'invert_lens_desc':
          'If icons/text appear upside down when holding and moving the selection — toggle this parameter.',
      'save': 'Save',
      'settings_page': 'Settings',
      'your_name': 'Your name',
      'birthday': 'Birthday',
      'your_birth_date': 'Your birth date',
      'specify': 'Specify',
      'appearance': 'Appearance',
      'notifications': 'Notifications',
      'allow_notifications': 'Allow notifications in OS settings',
      'start_chat': 'Start chat',
      'nothing_found': 'Nothing found',
      'chat_data_copied': 'Chat data copied',
      'share': 'Share',
      'shop': 'Shop',
      'no_sticker_packs': 'No sticker packs yet',
      'added': 'Added',
      'add': 'Add',
      'get': 'Get',
      'cache_error': 'Cache: ',
      'edit': 'Edit',
      'notification_permission': 'Allow notifications in OS settings',
      'shop_load_error': 'Shop loading error: ',
      'no_data': 'No data',
      'other_settings': 'Other',
      'questions_about_mycircle': 'Questions about MyCircle',
      'close_search': 'Close search',
      'search': 'Search',
      'energy_saving': 'Energy saving',
      'energy_saving_settings_later':
          'Energy saving settings will be added later.',
      'warning': 'Warning',
      'delete_data_warning':
          'Your data: name, birthday, chat data, Sup. API and Sup. pub_key will be deleted. You will need to re-enter a user\'s server and go through registration again.',
      'name': 'Name',
      'accessibility': 'Accessibility',
      'enable_notifications': 'Enable notifications',
      'disable_notifications': 'Disable notifications',
      'data_and_memory': 'Data and memory',
      'language_short': 'Language',
      'mycircle_channel': 'MyCircle channel',
      'sticker_load_error': 'Sticker loading error:',
      'add_sticker_packs_hint':
          'Add sticker packs in the "Shop" to make them appear here',
      'clear_cache_with_size': 'Clear cache',
      'cache_prefix': 'Cache: ',
      'byte_unit_b': 'B',
      'byte_unit_kb': 'KB',
      'byte_unit_mb': 'MB',
      'byte_unit_gb': 'GB',
      'byte_unit_tb': 'TB',
      'gb_unit': 'GB',
      'tapflow': 'TapFlow',
      'file_saved': 'File saved.',
      'error': 'Error',
      'transfer_failed': 'Transfer failed.',
      'hint': 'Hint',
      'tapflow_share_hint':
          'To send, use the system "Share" and select TapFlow.',
      'progress': 'Progress',
      'ready_to_receive': 'Ready to receive',
      'tap_detected': 'Tap detected',
      'transfer_request': 'Transfer request',
      'connecting': 'Connecting',
      'transferring': 'Transferring',
      'tapflow_standby': 'Open TapFlow to be ready to receive.',
      'tapflow_waiting':
          'Bring your phone close to the sender device.\nTapFlow will automatically detect the context.',
      'establishing_connection': 'Establishing connection…',
      'wants_to_transfer': 'wants to transfer',
      'connecting_to_sender': 'Connecting to sender…',
      'receiving_file': 'Receiving file…',
      'file_received': 'File received and saved.',
      'device': 'Device',
      'supabase_data': 'Supabase data',
      'decline': 'Decline',
      'accept': 'Accept',
      'my_profile': 'My profile',
      'switch_to_light_theme': 'Switch to light theme',
      'switch_to_dark_theme': 'Switch to dark theme',
      'reset': 'Reset',
      'failed_to_apply_drawing': 'Failed to apply drawing',
      'clear_all': 'Clear all',
      'no_media': 'No media',
      'sticker_label': 'Sticker',
      'media_label': 'Media',
      'load_btn': 'Load',
      'chat_fallback': 'Chat',
      'search_chats_hint': 'Search chats',
      'chats': 'Chats',
      'delete_chat_title_single': 'Delete chat',
      'delete_chat_title_plural': 'Delete chats',
      'remove_chat_confirm_single': 'Remove chat from device list?',
      'remove_chat_confirm_plural': 'Remove \$count chats from device list?',
      'delete_btn': 'Delete',
      'all_filter': 'All',
      'channels': 'Channels',
      'notes': 'Notes',
      'you': 'You',
      'interlocutor': 'Interlocutor',
      'photo_reply': 'Photo',
      'message_reply': 'Message',
      'add_chat_first_hint': 'First add a chat via "Add chat"',
      'editing': 'Editing',
      'no_messages_yet': 'No messages yet',
      'failed_to_decrypt': 'Failed to decrypt message',
      'members_count': '\$count members',
      'chat_token_label': 'Chat token',
      'chat_id_label': 'Chat ID',
      'members_section': 'Members',
      'files_section': 'Files',
      'not_working_yet': 'Not working yet',
      'members_not_available': 'Members unavailable (no member_tokens column in Supabase chats table)',
      'no_one_here_yet': 'No one here yet',
      'hd_photo_info': 'Photo will be in high resolution.',
      'sd_photo_info': 'Photo will be in standard resolution.',
      'add_caption_hint': 'Add a caption…',
      'downloaded_mycircle': 'Downloaded to MyCircle',
      'download_failed_label': 'Download failed',
      'download_error_label': 'Download error: \$e',
      'download_title': 'Download',
      'sticker_reply': 'Sticker',
      'notes_empty': 'You haven\'t added anything to notes yet',
      'edit_message_label': 'Edit message',
      'bold': 'Bold',
      'strikethrough': 'Strikethrough',
      'hidden_spoiler': 'Hidden (spoiler)',
      'reply_to_prefix': 'Reply to',
      'message_hint': 'Message',
      'no_connection_error': 'No network connection or poor signal. Check your network',
      'error_loading_messages': 'Error loading messages',
      'copied': 'Copied',
      'delete_message_title': 'Delete message',
      'delete_message_confirm': 'Are you sure you want to delete this message?',
      'failed_to_delete': 'Failed to delete: \$e',
      'failed_to_send_message': 'Failed to send message: \$e',
      'edge_function_no_url': 'Edge Function did not return raw_url',
      'failed_to_send_file': 'Failed to send file',
      'failed_to_open_gallery_file': 'Failed to open file from gallery',
      'no_gallery_access': 'No access to gallery',
      'failed_to_send_sticker': 'Failed to send sticker',
      'refresh': 'Refresh',
      'invalid_link': 'Invalid link',
      'failed_to_open_link': 'Failed to open link',
      'dark_mode': 'Dark mode',
      'me': 'Me',
      'quick_access': 'Quick access',
      'close_tooltip': 'Close',
      'in_development': 'In development',
      'bottom_menu': 'Bottom menu',
      'day_picker': 'Day',
      'month_picker': 'Month',
      'year_picker': 'Year',
      'confirm_btn': 'Confirm',
      'create_chat': 'Create chat',
      'join_chat': 'Join chat',
      'search_label': 'Search',
      'title_label': 'Title',
      'name_prefix': 'Title: \$title',
      'server': 'Server',
      'server_setup_desc': 'Log in to a server or create one to start communicating with loved ones',
      'create_server': 'Create server',
      'login_to_server': 'Log in to server',
      'docs': 'Documentation',
      'server_docs_desc': 'Read the documentation on creating a server so everything works',
      'supabase_url_hint': 'paste the link without "/rest/v1/"',
      'continue_btn': 'Continue',
      'save_error': 'Save error: \$e',
      'server_error': 'Server error: \$e',
      'enter_via_tapflow': 'Enter via TapFlow',
      'firebase_note': 'Firebase is already used in the app (push notifications), but these data are configured in the project and do not need to be entered here.',
      'what_to_call_you': 'What should we call you?',
      'name_hint': 'Name',
      'theme_and_color_prompt': 'What theme and button color suits you?',
      'light': 'Light',
      'dark': 'Dark',
      'button_colors': 'Button color',
      'choose_input_field': 'Choose input field',
      'normal': 'Normal',
      'advanced': 'Advanced',
      'ios_panel': 'IOS panel',
      'choose_navigation': 'Choose navigation panel',
      'sliding': 'Sliding',
      'thanks_for_your_time': 'Thank you for your time',
      'copy_btn': 'Copy',
      'loading': 'Loading...',
      'registration': 'Registration',
      'file_fallback': 'file',
      'token_label': 'Token',
      'remove_tooltip': 'Remove',
      'token_n_label': 'Token \$n',
      'add_token_tooltip': 'Add token',
      'prompt_label': 'Prompt',
      'nameless': 'No name',
      'info_section': 'Information',
      'not_specified': 'Not specified',
      'birth_date_label': 'Birth date',
      'send_via_tapflow': 'Send via TapFlow',
      'copy_and_share': 'Copy and share',
      'share_btn': 'share',
      'stickers_count': 'Stickers: \$count',
      'pack_added': 'Pack added',
      'pack_download_failed': 'Failed to download pack',
      'fill_all_fields': 'Fill in all fields',
      'problem_too_long': 'Brief problem: maximum 20 characters',
      'invalid_email': 'Enter a valid email',
      'sent': 'Sent',
      'send_error': 'Send error. Try again later.',
      'problem_label': 'Brief problem',
      'email_label': 'Email',
      'problem_hint': 'Describe the problem in detail',
      'send_btn': 'Send',
      'unsubscribe_channel': 'Unsubscribe from channel',
      'unsubscribe_confirm': 'Are you sure you want to leave the MyCircle channel?',
      'leave_btn': 'Leave',
      'search_in_chat_hint': 'Search in chat',
      'subscribed': 'Subscribed',
      'subscribe': 'Subscribe',
      'description_label': 'description',
      'channel_description': 'Messenger news, changes and other updates',
      'dev_notice_title': 'Notice',
      'dev_notice_text': 'This messenger is not fully finished and may look unpolished, has bugs and more. Therefore, please report these shortcomings and suggest your ideas so the messenger is convenient for everyone.',
      'close_btn': 'Close',
      'version_label': 'Version \$version',
      'chat_exists_error': 'A chat with this ID already exists',
      'create_chat_error': 'Failed to create chat',
      'chat_not_found_server': 'Chat with this ID not found on server',
      'no_chat_uuid': 'Failed to get chat UUID',
      'invalid_chat_token': 'Invalid chat token',
      'error_fallback': 'Error',
      'chat_id_required': 'Chat ID is required',
      'chat_name_required': 'Chat name is required',
      'chat_token_required': 'Chat token is required',
      'sup_api_label': 'Sup. API',
      'sup_pub_key_label': 'Sup. pub_key',
      'channel_left': 'You left the channel',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'about_text':
          'MyCircle is a decentralized messaging platform focused on ensuring complete privacy and sovereignty of user data.\n'
          '\n'
          'Key principles:\n'
          'Own infrastructure: MyCircle is based on the concept of personal servers. You deploy the server part yourself, allowing you to fully control the communication environment and participant circle.\n'
          'Privacy: The app developer does not collect, store, or process your data. All information (messages, media files, metadata) is stored exclusively on the server chosen or created by the user.\n'
          'Security through trust: You decide who to grant access to your server, eliminating the possibility of unauthorized access by third parties or global providers.\n'
          '\n'
          'Technology stack:\n'
          'The application is built on the Flutter framework, ensuring high performance, stability, and responsive interface.',
    },
    'be': {
      'language': 'Мова',
      'language_interface': 'МОВА ІНТЭРФЭЙСУ',
      'privacy': 'Прыватнасць',
      'passcode': 'Пароль',
      'auto_cleanup': 'Аўтаачыстка',
      'auto_cleanup_title': 'Аўтаачыстка памяці',
      'what_to_delete': 'Што выдаляць аўтаматычна',
      'nothing_selected': 'Нічога не выбрана',
      'type': 'тып',
      'types': 'тыпы',
      'type_many': 'тыпаў',
      'video': 'Відэа',
      'photo': 'Фота',
      'files': 'Файлы',
      'stickers': 'Стыкеры',
      'other_cleanup': 'Іншае',
      'cleanup_warning':
          'Важна: выдаляецца толькі тое, што Вы выбралі і ў той час, які Вы паставілі. Вы зможаце зноў спампаваць з чатаў тое, што выдалена.',
      'cleanup_time': 'Час аўтавыдалення',
      'off': 'Выкл',
      'after_1_day': 'Праз 1 дзень',
      'after_5_days': 'Праз 5 дзён',
      'after_10_days': 'Праз 10 дзён',
      'after_20_days': 'Праз 20 дзён',
      'done': 'Гатова',
      'cancel': 'Адмена',
      'back': 'Назад',
      'settings': 'Налады',
      'profile': 'Профіль',
      'help': 'Дапамога',
      'about': 'Пра праграму',
      'memory_usage': 'Выкарыстанне памяці',
      'clear_cache': 'Ачысціць кэш',
      'clear_cache_confirm':
          'Усе медыя застануцца ў хмары MyCircle, пры неабходнасці Вы зможаце зноў спампаваць іх з чатаў',
      'cancel_btn': 'Адмена',
      'clear_btn': 'Ачысціць',
      'no_downloaded_media': 'Няма спампаваных медыя',
      'download': 'Спампаваць',
      'downloaded_to_mycircle': 'Спампавана ў MyCircle',
      'download_failed': 'Не ўдалося спампаваць',
      'download_error': 'Памылка спампоўвання',
      'max_cache_size': 'Максімальны памер кэша',
      'max_cache_desc':
          'Калі памер кэша перавысіць гэты ліміт, то найстарэйшыя з неўжываных медыя будуць выдалены з памяці прылады',
      'media': 'Медыя',
      'files_tab': 'Файлы',
      'music': 'Музыка',
      'occupied': 'Занята',
      'files_soon': 'Файлы: хутка',
      'music_soon': 'Музыка: хутка',
      'disable_passcode': 'Адключыць пароль',
      'change_passcode': 'Змяніць пароль',
      'passcode_settings': 'Налады пароля',
      'auto_lock': 'Аўтаблакіроўка',
      'auto_lock_immediately': 'Адразу',
      'auto_lock_after_1_min': 'Праз 1 хвіліну',
      'auto_lock_after_5_min': 'Праз 5 хвілін',
      'auto_lock_after_15_min': 'Праз 15 хвілін',
      'auto_lock_after_1_hour': 'Праз 1 гадзіну',
      'auto_lock_after_5_hours': 'Праз 5 гадзін',
      'enter_passcode': 'Увядзіце пароль',
      'set_passcode': 'Устанавіце пароль',
      'confirm_passcode': 'Пацвердзіце пароль',
      'passcodes_dont_match': 'Паролі не супадаюць',
      'passcode_changed': 'Пароль зменены',
      'passcode_disabled': 'Пароль адключаны',
      'passcode_warning':
          'Важна: калі Вы забудзеце пароль, Вам давядзецца пераўстанавіць праграму і прасіць ключы сервера зноў.',
      'enter_new_passcode': 'Увядзіце новы пароль',
      'navigation_panel': 'Панэль навігацыі',
      'change_navigation_panel': 'Змяніць панэль навігацыі',
      'chat_settings': 'Налады чатаў:',
      'change_wallpaper': 'Змяніць шпалеры',
      'memory_and_security': 'Памяць і бяспека',
      'ios_navigation_panel': 'Панэль навігацыі IOS',
      'ios_navigation_panel_desc':
          'Частковая копія панэлі навігацыі iOS 26 з тэхналогіяй Liquid Glass ("Вадкае шкло"). Не рэкамендуецца для прылад з нізкай прадуктыўнасцю: гэта можа выклікаць рост нагрузкі на сістэму.',
      'invert_lens': 'Інвертаваць лінзу вертыкальна',
      'invert_lens_desc':
          'Калі пры ўтрыманні і перамяшчэнні вылучэння іконка/тэкст адлюстроўваюцца ўверх нагамі — пераключы гэты параметр.',
      'save': 'Захаваць',
      'settings_page': 'Налады',
      'your_name': 'Ваша імя',
      'birthday': 'Дзень нараджэння',
      'your_birth_date': 'Дата Вашага нараджэння',
      'specify': 'Указаць',
      'appearance': 'Афармленне',
      'notifications': 'Апавяшчэнні',
      'allow_notifications': 'Дазвольце апавяшчэнні ў наладах АС',
      'start_chat': 'Пачаць размову',
      'nothing_found': 'Нічога не знойдзена',
      'chat_data_copied': 'Дадзеныя чата скапіраваны',
      'share': 'Падзяліцца',
      'shop': 'Магазін',
      'no_sticker_packs': 'Пакуль няма набораў стыкераў',
      'added': 'Дададзена',
      'add': 'Дадаць',
      'get': 'Атрымаць',
      'cache_error': 'Кэш: ',
      'edit': 'Рэд.',
      'notification_permission': 'Дазвольце апавяшчэнні ў наладах АС',
      'shop_load_error': 'Памылка загрузкі магазіну: ',
      'no_data': 'Няма дадзеных',
      'other_settings': 'Іншае',
      'questions_about_mycircle': 'Пытанні пра MyCircle',
      'close_search': 'Закрыць пошук',
      'search': 'Пошук',
      'energy_saving': 'Энергазберажэнне',
      'energy_saving_settings_later':
          'Налады энергазберажэння будуць дададзены пазней.',
      'warning': 'Папярэджанне',
      'delete_data_warning':
          'Вашы дадзеныя: імя, дата нараджэння, дадзеныя з чатаў, Sup. API і Sup. pub_key будуць выдалены. Вам давядзецца зноў уваходзіць на сервер якога-небудзь карыстальніка і праходзіць рэгістрацыю.',
      'name': 'Імя',
      'accessibility': 'Спецыяльныя магчымасці',
      'enable_notifications': 'Уключыць апавяшчэнні',
      'disable_notifications': 'Адключыць апавяшчэнні',
      'data_and_memory': 'Дадзеныя і памяць',
      'language_short': 'Мова',
      'mycircle_channel': 'Канал MyCircle',
      'sticker_load_error': 'Памылка загрузкі стыкераў:',
      'add_sticker_packs_hint':
          'Дадай наборы стыкераў у «Магазіне», каб яны з\'явіліся тут',
      'clear_cache_with_size': 'Ачысціць кэш',
      'cache_prefix': 'Кэш: ',
      'byte_unit_b': 'Б',
      'byte_unit_kb': 'КБ',
      'byte_unit_mb': 'МБ',
      'byte_unit_gb': 'ГБ',
      'byte_unit_tb': 'ТБ',
      'gb_unit': 'ГБ',
      'tapflow': 'TapFlow',
      'file_saved': 'Файл захаваны.',
      'error': 'Памылка',
      'transfer_failed': 'Не ўдалося выканаць перадачу.',
      'hint': 'Падказка',
      'tapflow_share_hint':
          'Для адпраўкі выкарыстайце сістэмную «Падзяліцца» і выберыце TapFlow.',
      'progress': 'Прагрэс',
      'ready_to_receive': 'Гатовы да прыёму',
      'tap_detected': 'Дотык выяўлены',
      'transfer_request': 'Запыт на перадачу',
      'connecting': 'Падключэнне',
      'transferring': 'Перадача',
      'tapflow_standby': 'Адкрыйце TapFlow, каб быць гатовых да прыёму.',
      'tapflow_waiting':
          'Паднесіце тэлефон да прылады адпраўніка.\nTapFlow аўтаматычна зразумее кантэкст.',
      'establishing_connection': 'Усталёўваю злучэнне…',
      'wants_to_transfer': 'хача перадаць',
      'connecting_to_sender': 'Падключаюся да адпраўніка…',
      'receiving_file': 'Атрымліваю файл…',
      'file_received': 'Файл атрыманы і захаваны.',
      'device': 'Прылада',
      'supabase_data': 'Дадзеныя Supabase',
      'decline': 'Адхіліць',
      'accept': 'Прыняць',
      'my_profile': 'Мой профіль',
      'switch_to_light_theme': 'Пераключыць на дзённую тэму',
      'switch_to_dark_theme': 'Пераключыць на начную тэму',
      'reset': 'Скінуць',
      'failed_to_apply_drawing': 'Не ўдалося прымяніць малюнак',
      'clear_all': 'Ачысціць усё',
      'no_media': 'Няма медыя',
      'sticker_label': 'Стыкер',
      'media_label': 'Медыя',
      'load_btn': 'Загрузіць',
      'chat_fallback': 'Чат',
      'search_chats_hint': 'Пошук чатаў',
      'chats': 'Чаты',
      'delete_chat_title_single': 'Выдаліць чат',
      'delete_chat_title_plural': 'Выдаліць чаты',
      'remove_chat_confirm_single': 'Прыбраць чат са спісу на прыладзе?',
      'remove_chat_confirm_plural': 'Прыбраць \$count чатаў са спісу на прыладзе?',
      'delete_btn': 'Выдаліць',
      'all_filter': 'Усе',
      'channels': 'Каналы',
      'notes': 'Нататкі',
      'you': 'Вы',
      'interlocutor': 'Субяседнік',
      'photo_reply': 'Фота',
      'message_reply': 'Паведамленне',
      'add_chat_first_hint': 'Спачатку дадайце чат праз «Дадаць чат»',
      'editing': 'Рэдагаванне',
      'no_messages_yet': 'Пакуль няма паведамленняў',
      'failed_to_decrypt': 'Не ўдалося расшыфраваць паведамленне',
      'members_count': '\$count удзельнікаў',
      'chat_token_label': 'Токен чата',
      'chat_id_label': 'ID чата',
      'members_section': 'Удзельнікі',
      'files_section': 'Файлы',
      'not_working_yet': 'Пакуль не працуе',
      'members_not_available': 'Удзельнікі недаступныя (у Supabase няма калонкі member_tokens у табліцы chats)',
      'no_one_here_yet': 'Пакуль нікога няма',
      'hd_photo_info': 'Фатаграфія будзе ў высокім разрозненні.',
      'sd_photo_info': 'Фатаграфія будзе ў звычайным разрозненні.',
      'add_caption_hint': 'Дадаць подпіс…',
      'downloaded_mycircle': 'Спампавана ў MyCircle',
      'download_failed_label': 'Не ўдалося спампаваць',
      'download_error_label': 'Памылка спампоўкі: \$e',
      'download_title': 'Спампаваць',
      'sticker_reply': 'Стыкер',
      'notes_empty': 'Вы яшчэ нічога не дадалі ў нататкі',
      'edit_message_label': 'Змяніць паведамленне',
      'bold': 'Тоўсты',
      'strikethrough': 'Закрэслены',
      'hidden_spoiler': 'Схаваны (спойлер)',
      'reply_to_prefix': 'У адказ',
      'message_hint': 'Паведамленне',
      'no_connection_error': 'Падключэнне да сеткі адсутнічае або дрэнная сувязь. Праверце сваю сетку',
      'error_loading_messages': 'Памылка загрузкі паведамленняў',
      'copied': 'Скапіравана',
      'delete_message_title': 'Выдаліць паведамленне',
      'delete_message_confirm': 'Вы дакладна хочаце выдаліць гэтае паведамленне?',
      'failed_to_delete': 'Не ўдалося выдаліць: \$e',
      'failed_to_send_message': 'Не ўдалося адправіць паведамленне: \$e',
      'edge_function_no_url': 'Edge Function не вярнула raw_url',
      'failed_to_send_file': 'Не ўдалося адправіць файл',
      'failed_to_open_gallery_file': 'Не ўдалося адкрыць файл з галерэі',
      'no_gallery_access': 'Няма доступу да галерэі',
      'failed_to_send_sticker': 'Не ўдалося адправіць стыкер',
      'refresh': 'Абнавіць',
      'invalid_link': 'Няправільная спасылка',
      'failed_to_open_link': 'Не ўдалося адкрыць спасылку',
      'dark_mode': 'Цёмны рэжым',
      'me': 'Я',
      'quick_access': 'Хуткі доступ',
      'close_tooltip': 'Закрыць',
      'in_development': 'У распрацоўцы',
      'bottom_menu': 'Ніжняе меню',
      'day_picker': 'Дзень',
      'month_picker': 'Месяц',
      'year_picker': 'Год',
      'confirm_btn': 'Пацвердзіць',
      'create_chat': 'Стварыць чат',
      'join_chat': 'Далучыцца да чата',
      'search_label': 'Пошук',
      'title_label': 'Назва',
      'name_prefix': 'Назва: \$title',
      'server': 'Сервер',
      'server_setup_desc': 'Увайдзіце на сервер або стварыце яго, каб пачаць зносіны з блізкімі людзьмі',
      'create_server': 'Стварыць сервер',
      'login_to_server': 'Увайсці на сервер',
      'docs': 'Дакументацыя',
      'server_docs_desc': 'Прачытайце дакументацыю па стварэнні сервера, каб усё працавала',
      'supabase_url_hint': 'устаўляйце спасылку без "/rest/v1/"',
      'continue_btn': 'Працягнуць',
      'save_error': 'Памылка захавання: \$e',
      'server_error': 'Памылка сервера: \$e',
      'enter_via_tapflow': 'Увесці праз TapFlow',
      'firebase_note': 'Firebase ужо выкарыстоўваецца ў праграме (push-апавяшчэнні), але гэтыя даныя наладжваюцца ў праекце і сюды ўводзіць не трэба.',
      'what_to_call_you': 'Як вас называць?',
      'name_hint': 'Імя',
      'theme_and_color_prompt': 'Якая тэма і колер кнопак вам падыходзіць?',
      'light': 'Светлая',
      'dark': 'Цёмная',
      'button_colors': 'Колер кнопак',
      'choose_input_field': 'Выберыце поле ўводу',
      'normal': 'Звычайнае',
      'advanced': 'Пашыранае',
      'ios_panel': 'IOS панэль',
      'choose_navigation': 'Выберыце панэль навігацыі',
      'sliding': 'Высоўныя',
      'thanks_for_your_time': 'Дзякуй за нададзены час',
      'copy_btn': 'Капіяваць',
      'loading': 'Загрузка...',
      'registration': 'Рэгістрацыя',
      'file_fallback': 'файл',
      'token_label': 'Токен',
      'remove_tooltip': 'Выдаліць',
      'token_n_label': 'Токен \$n',
      'add_token_tooltip': 'Дадаць токен',
      'prompt_label': 'Промпт',
      'nameless': 'Без імя',
      'info_section': 'Інфармацыя',
      'not_specified': 'Не ўказана',
      'birth_date_label': 'Дата нараджэння',
      'send_via_tapflow': 'Перадаць праз TapFlow',
      'copy_and_share': 'Скапіяваць і падзяліцца',
      'share_btn': 'падзяліцца',
      'stickers_count': 'Стыкераў: \$count',
      'pack_added': 'Набор дададзены',
      'pack_download_failed': 'Не ўдалося спампаваць набор',
      'fill_all_fields': 'Запоўніце ўсе палі',
      'problem_too_long': 'Кароткая праблема: максімум 20 сімвалаў',
      'invalid_email': 'Увядзіце правільную пошту',
      'sent': 'Адпраўлена',
      'send_error': 'Памылка адпраўкі. Паспрабуйце пазней.',
      'problem_label': 'Кароткая праблема',
      'email_label': 'Пошта',
      'problem_hint': 'Падрабязна апішыце праблему',
      'send_btn': 'Адправіць',
      'unsubscribe_channel': 'Адпіска ад канала',
      'unsubscribe_confirm': 'Вы дакладна хочаце пакінуць канал MyCircle?',
      'leave_btn': 'Пакінуць',
      'search_in_chat_hint': 'Шукаць у чаце',
      'subscribed': 'Падпісаны',
      'subscribe': 'Падпісацца',
      'description_label': 'апісанне',
      'channel_description': 'Навіны па месэнджары, змены і іншыя абнаўленні',
      'dev_notice_title': 'Апавяшчэнне',
      'dev_notice_text': 'Гэты месэнджар зроблены не да канца і, магчыма, выглядае непрыгожа, маюцца памылкі і многае іншае. Таму, калі ласка, паведамляйце аб гэтых недахопах і прапануйце свае ідэі, каб месэнджар быў зручным усім.',
      'close_btn': 'Закрыць',
      'version_label': 'Версія \$version',
      'chat_exists_error': 'Чат з такім ID ужо існуе',
      'create_chat_error': 'Не ўдалося стварыць чат',
      'chat_not_found_server': 'Чат з такім ID не знойдзены на серверы',
      'no_chat_uuid': 'Не ўдалося атрымаць UUID чата',
      'invalid_chat_token': 'Няправільны токен чата',
      'error_fallback': 'Памылка',
      'chat_id_required': 'ID чата абавязковы',
      'chat_name_required': 'Назва чата абавязковая',
      'chat_token_required': 'Токен чата абавязковы',
      'sup_api_label': 'Sup. API',
      'sup_pub_key_label': 'Sup. pub_key',
      'channel_left': 'Вы пакінулі канал',
      'january': 'студзеня',
      'february': 'лютага',
      'march': 'сакавіка',
      'april': 'красавіка',
      'may': 'мая',
      'june': 'чэрвеня',
      'july': 'ліпеня',
      'august': 'жніўня',
      'september': 'верасня',
      'october': 'кастрычніка',
      'november': 'лістапада',
      'december': 'снежня',
      'about_text':
          'MyCircle — гэта дэцэнтралізаваная платформа для абмену паведамленнямі, нацэленая на забеспячэнне поўнай прыватнасці і суверэнітэту даных карыстальнікаў.\n'
          '\n'
          'Ключавыя прынцыпы:\n'
          'Уласная інфраструктура: У аснове MyCircle ляжыць канцэпцыя персанальных сервераў. Вы самастойна разгортваеце серверную частку, што дазваляе вам цалкам кантраляваць асяроддзе зносін і круг удзельнікаў.\n'
          'Прыватнасць: Распрацоўшчык праграмы не ажыццяўляе збор, захаванне або апрацоўку вашых даных. Уся інфармацыя (паведамленні, медыяфайлы, метададзеныя) захоўваецца выключна на серверы, выбраным або створаным карыстальнікам.\n'
          'Бяспека праз давер: Вы самі вызначаеце, каму даць доступ да вашага сервера, выключаючы магчымасць несанкцыянаванага доступу з боку трэціх асоб або глабальных правайдэраў.\n'
          '\n'
          'Тэхналагічны стэк:\n'
          'Праграма распрацавана на фрэймворку Flutter, што забяспечвае высокую прадукцыйнасць, стабільнасць працы і адказнасць інтэрфейсу.',
    },
  };

  String get(String key) {
    return _translations[locale]?[key] ?? _translations['ru']?[key] ?? key;
  }
}
